name       : python-twodict
version    : 1.2
release    : 1
source     :
    - https://pypi.python.org/packages/49/96/03307c666c1ce0c04bdc23fb69f758b4076eff39d15c56f943ba4b527e21/twodict-1.2.tar.gz : 20dbdfa7f14a285454d34bba1e7714aad15a376ddfd0a1c0a3c24a14763bdb45
license    : Unlicense
component  : programming.python
summary    : Simple two way ordered dictionary for Python
description: |
    Simple two way ordered dictionary for Python
build      : |
    %python_setup
install    : |
    %python_install
